[run]
skip-dirs = [ "db/generated" ]

[linters-settings.errcheck]
exclude-functions = [
  # AbortWithError and Error also returns the Error
  "(*github.com/gin-gonic/gin.Context).AbortWithError",
  "(*github.com/gin-gonic/gin.Context).Error"
]
