#!/bin/sh
echo "go mod tidy"
go mod tidy
echo "go generate app"
go generate cmd/app/main.go
echo "go fmt"
go fmt ./...
echo "go vet"
go vet ./...
echo "lint"
go run github.com/golangci/golangci-lint/cmd/golangci-lint run 
