#!/bin/sh
export ENVIRONMENT=local
export PORT=8080
export APP_URL=http://localhost:"$PORT"
export SERVICE_NAME=TestApp
export EMAIL_FROM=test-email-from@example.com
export MOCK_API_PORT=8081
export EMAIL_API_URL=http://localhost:"$MOCK_API_PORT"/mock-send-email
export DB_NAME=db
export DB_HOST=localhost
export DB_PORT=27017
export DB_USER=test
DB_PASSWORD=$(head -c 15 < /dev/random | base64)
export DB_PASSWORD

DOCKER_MONGO_NAME=mongo-local-dev

killIfExists() {
    if [ -n "$1" ]
    then
      kill "$1"
    fi
}

cleanup() {
    echo "------ CLEANUP ------"
    echo "------ KILLING PROCESSES ------"
    killIfExists "$_APP_PID"
    killIfExists "$_EMAILER_PID"
    killIfExists "$_MOCK_THIRD_PARTY_APIS"

    sleep 2
    echo "------ REMOVING DOCKER CONTAINERS ------"
    docker rm $DOCKER_MONGO_NAME -f > /dev/null
}

trap cleanup EXIT

echo "------ START LOCAL DB ($DOCKER_MONGO_NAME) ------"
if docker run -p $DB_PORT:$DB_PORT --name $DOCKER_MONGO_NAME \
  -e MONGO_INITDB_ROOT_USERNAME=test \
	-e MONGO_INITDB_ROOT_PASSWORD="$DB_PASSWORD" \
  -d mongo
then
    echo "------ START MOCK 3RD-PARTY API ------"
    go run cmd/mock-3rd-party-apis/main.go &
    _MOCK_THIRD_PARTY_APIS=$!
    echo "------ START APP ------"
    go run cmd/app/main.go &
    _APP_PID=$!
    echo "------ START EMAILER ------"
    go run cmd/email-job/main.go &
    _EMAILER_PID=$!

    sleep infinity
else
  echo "----- ABORTING -----"
fi
