#!/bin/sh
export ENVIRONMENT=local
export PORT=8080
export APP_URL=http://localhost:8080
export SERVICE_NAME=TestApp
export EMAIL_FROM=test-email-from@example.com
export EMAIL_API_URL=http://localhost:8081/mock-send-email
export MOCK_API_PORT=8081
export DB_NAME=postgres
export DB_HOST=localhost
export DB_PORT=5432
export DB_USER=postgres
export DB_PASSWORD=$(cat /dev/random | head -c 15 | base64)
_DOCKER_POSTGRES_NAME=postgres-local-dev-$(cat /proc/sys/kernel/random/uuid)

killIfExists() {
    if [[ -n "$1" ]]
    then
      kill $1
    fi
}

cleanup() {
    echo "------ CLEANUP ------"
    echo "------ KILLING PROCESSES ------"
    killIfExists $_APP_PID
    killIfExists $_EMAILER_PID
    killIfExists $_MOCK_THIRD_PARTY_APIS

    sleep 2
    echo "------ REMOVING DOCKER CONTAINERS ------"
    docker rm $_DOCKER_POSTGRES_NAME -f > /dev/null
}

trap cleanup exit

echo "------ START LOCAL DB ($_DOCKER_POSTGRES_NAME) ------"
docker run --name $_DOCKER_POSTGRES_NAME -p 5432:5432 -e POSTGRES_PASSWORD=$DB_PASSWORD -d postgres > /dev/null

echo "------ RUN MIGRATOR ------"
go run cmd/migrator/main.go

if [[ $? = 0 ]]
then
    echo "------ START MOCK EMAIL API ------"
    go run cmd/mock-3rd-party-apis/main.go &
    _MOCK_THIRD_PARTY_APIS=$!
    echo "------ START APP ------"
    go run cmd/app/main.go &
    _APP_PID=$!
    echo "------ START EMAILER ------"
    go run cmd/email-job/main.go &
    _EMAILER_PID=$!

    sleep infinity
else
  echo "----- ABORTING -----"
fi
